/* ═══════════════════════════════════════
   GLOW NOTES — data.js
═══════════════════════════════════════ */

// Top 8 curated featured reels shown on landing feed
// Full library used for fallback generation
const FEATURED_IDS = [
  'proud-of-you',
  'storm-will-pass',
  'you-are-enough',
  'the-leap',
  'your-light',
  'broken-open',
  'look-at-you',
  'start-here'
];

const DEFAULT_REELS = [
  {id:'proud-of-you',tag:'A Letter to You',title:"I'm <span class='glow-word'>Proud</span> of You",body:["I've seen the battles you've fought \u2014 the quiet ones, the ones no one else knew were happening. You carried so much and still managed to find <span class='glow-word'>light</span> in your days.","You've grown in ways that amaze me. You turned struggle into wisdom, fear into focus, pain into patience. You're building yourself into someone <span class='glow-word'>strong and steady</span>.","I know there were days you wondered if anyone noticed, if all the effort was worth it. But I see it. I see how far you've come. I see the <span class='glow-word'>strength</span> behind your smile.","So please don't forget this, even on the hard days: you're doing incredible. You're becoming the kind of person others look up to without even realizing it."],signature:"And I'm proud of you \u2014 deeply, always.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'new-chapter',tag:'A New Beginning',title:"This Is Your <span class='glow-word'>New Chapter</span>",body:["Every story has a turning point \u2014 a page where everything shifts. You're standing at yours right now, and even if it doesn't feel like it, this is one of the most <span class='glow-word'>significant moments</span> of your life.","Not because everything is perfect. But because you chose to keep going. You chose to believe that what's ahead is worth reaching for.","New chapters don't announce themselves with fanfare. They begin quietly \u2014 with a decision, a step, a breath. <span class='glow-word'>This is yours</span>."],signature:"Turn the page. The best part is still unwritten.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'seeds-growing',tag:'For the Patient Ones',title:"Good Things Are <span class='glow-word'>Growing</span>",body:["Seeds don't announce when they're about to bloom. They work in silence, underground, unseen \u2014 and then one day, without warning, something <span class='glow-word'>breaks through</span>.","You've been planting. Every hard day you got through, every moment you chose to try again \u2014 that was planting. You may not see the results yet, but the roots are real.","Trust the process you can't always see. <span class='glow-word'>Something beautiful is on its way</span>."],signature:"Spring always follows winter. Always.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'you-are-allowed',tag:'Permission Slip',title:"You Are <span class='glow-word'>Allowed</span>",body:["You are allowed to want more. You are allowed to outgrow the person you used to be. You are allowed to dream bigger than your circumstances seem to permit.","You're allowed to be proud of how far you've come <span class='glow-word'>and</span> still want to go further. You're allowed to rest without guilt.","Nobody gave you a rulebook that said you had to have it all figured out by now. You're doing this in real time, with a <span class='glow-word'>real heart</span>."],signature:"Give yourself the permission no one else will.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'almost-there',tag:'Keep Going',title:"You're <span class='glow-word'>Closer</span> Than You Think",body:["The hardest part of any journey isn't the beginning \u2014 it's the middle. The part where the excitement has worn off and the finish line isn't visible yet.","This is where most people stop. Not because they can't, but because they can't <span class='glow-word'>see</span> how close they actually are.","Keep moving. Not perfectly, not quickly \u2014 just <span class='glow-word'>forward</span>. You're closer than you've ever been."],signature:"The finish line exists. Keep running.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'future-self',tag:'A Letter from Ahead',title:"Your Future Self <span class='glow-word'>Wants You to Know</span>",body:["If your future self could send you a message right now \u2014 from the other side of all this \u2014 it would say: <span class='glow-word'>it worked out</span>.","Not perfectly. Not without scars. But it worked out in the way that actually matters \u2014 you grew through it, you became someone you're genuinely proud of.","Hold on. The version of you on the other side of this is <span class='glow-word'>so worth becoming</span>."],signature:"Your future self is rooting for you. Hard.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'ordinary-extraordinary',tag:'The Quiet Magic',title:"You Are <span class='glow-word'>Quietly Extraordinary</span>",body:["The world celebrates the loud kind of greatness. But there's another kind \u2014 the kind you carry every day without anyone noticing.","The way you show up for the people you love. The way you keep your word even when it costs you. That's not ordinary. <span class='glow-word'>That's extraordinary</span>.","It shapes every room you walk into, every life that's better because you're in it. <span class='glow-word'>Don't underestimate that</span>."],signature:"Quiet greatness is still greatness.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'worth-the-wait',tag:'For the Patient Heart',title:"Good Things Are <span class='glow-word'>Worth Waiting For</span>",body:["I know the waiting is hard. Waiting for the relationship to heal, the opportunity to arrive, the life you imagined to finally feel real.","But some things take time not because they're not coming \u2014 but because they're being made <span class='glow-word'>right</span>.","Hold on. <span class='glow-word'>It's worth the wait</span>."],signature:"What's coming is worth every day of waiting.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'you-are-enough',tag:'A Gentle Reminder',title:"You Are <span class='glow-word'>Enough</span>",body:["On the days when everything feels like too much \u2014 remember this: you have already survived every single hard day that came before this one.","That's not luck. That's <span class='glow-word'>you</span>. That's your resilience, your will, your stubborn refusal to let the hard days win permanently.","You don't need to be perfect. You just need to keep going \u2014 one breath, one step, one moment at a time. <span class='glow-word'>The version of you that's here right now</span> is the one the world needs."],signature:"Keep going. You're closer than you think.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'built-different',tag:'You Were Made For This',title:"You Were <span class='glow-word'>Built</span> Different",body:["Not everyone could carry what you've carried. Not everyone would have kept going under the weight of what you've faced. But you did.","The things that tried to break you only revealed what you're made of \u2014 something <span class='glow-word'>remarkably hard to break</span>.","This isn't about being fearless. It's about being afraid and doing it anyway. That's not ordinary. <span class='glow-word'>That's you</span>."],signature:"You are not fragile. You never were.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'rise-again',tag:'For the Ones Who Fall',title:"You Will <span class='glow-word'>Rise</span> Again",body:["Falling is not failure. Falling is part of every story worth telling. Every person you admire has a chapter they don't talk about.","They did have what it takes. And <span class='glow-word'>so do you</span>.","You're still here. You're still trying. That means <span class='glow-word'>you haven't given up</span>. And that matters more than anything."],signature:"Get up one more time. That's all it takes.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'warrior-quiet',tag:'The Quiet Fight',title:"No One Sees the <span class='glow-word'>Battle</span> You're Winning",body:["There's a kind of strength that doesn't get celebrated \u2014 the strength of <span class='glow-word'>showing up anyway</span>.","You've been fighting battles no one around you even knows exist. And every day you wake up and try \u2014 you're winning.","I see it. Even if you can't see it yourself \u2014 <span class='glow-word'>I see your strength</span>. And it's extraordinary."],signature:"The bravest fights are the ones no one sees.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'proof',tag:'The Evidence',title:"Look at the <span class='glow-word'>Proof</span>",body:["When you start to doubt yourself, look at the evidence. Not at what you haven't done. At what you <span class='glow-word'>have</span>.","You have survived things that seemed unsurvivable. You have chosen, again and again, to be <span class='glow-word'>more than what happened to you</span>.","That's proof that you are exactly the person this moment needs."],signature:"The evidence is clear. You're stronger than you know.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'still-here',tag:'Survival Is Enough',title:"The Fact That <span class='glow-word'>You're Still Here</span>",body:["The fact that you're still here \u2014 still trying, still breathing, still reaching for something better \u2014 that is <span class='glow-word'>not small</span>.","There were probably days when staying felt impossible. But you didn't give up.","You stayed. And <span class='glow-word'>that is everything</span>."],signature:"Stay. The next chapter needs you in it.",mood:'strength',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'your-light',tag:'For the Quiet Ones',title:"Your <span class='glow-word'>Light</span> Matters",body:["You might not see it \u2014 the way your kindness ripples outward, the way your presence shifts a room, the way someone breathes a little easier just because you showed up.","Your light isn't loud. It doesn't demand attention. It <span class='glow-word'>glows</span> \u2014 steady and warm \u2014 like sunrise through a window.","The people who matter see it. And even when you can't feel it yourself, trust that it's still shining. <span class='glow-word'>You were meant to be a safe place</span>."],signature:"Never dim your light for someone else's comfort.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'storm-will-pass',tag:'When It Gets Heavy',title:"The Storm <span class='glow-word'>Will Pass</span>",body:["Right now it might feel like the rain will never stop. I know how exhausting it is to keep walking when you can't see the road ahead.","But here's what storms do: they <span class='glow-word'>end</span>. Every single one. And when this one passes, you'll find that the ground beneath you is still solid.","You don't have to be brave every minute. You just have to hold on. Trust that <span class='glow-word'>morning always comes</span>."],signature:"After every storm, there is stillness. Yours is coming.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'not-alone',tag:'You Are Seen',title:"You Are <span class='glow-word'>Not Alone</span>",body:["I know it can feel that way \u2014 like you're carrying something no one else could possibly understand.","But you are <span class='glow-word'>more seen</span> than you realize. More loved than you feel right now.","You don't have to be okay. You just have to let someone in. Just <span class='glow-word'>one person</span>. Start there."],signature:"You were never meant to carry this alone.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'permission-to-rest',tag:'Rest Is Sacred',title:"It's Okay to <span class='glow-word'>Rest</span>",body:["You've been running for so long \u2014 toward deadlines, toward expectations, toward a version of yourself that always feels just out of reach.","Rest isn't a reward for productivity. <span class='glow-word'>Rest is survival</span>. It's how you refill the parts of yourself the world keeps emptying.","Stop. Breathe. You don't have to earn stillness. Just <span class='glow-word'>let yourself have it</span>."],signature:"Rest isn't giving up. It's how you keep going.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'tender-heart',tag:'For the Ones Who Feel Everything',title:"Your <span class='glow-word'>Tender Heart</span> Is a Gift",body:["You feel things deeply. And sometimes \u2014 in a world that rewards numbness \u2014 that feels like a curse.","But your sensitivity is not a weakness. It's <span class='glow-word'>how you love people well</span>. It's why strangers trust you. It's why the people in your life feel seen.","Don't let anyone convince you to feel <span class='glow-word'>less</span>. The world needs people who still know how to feel it all."],signature:"Feel it all. It means you're still alive.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'heavy-days',tag:'When You Can Barely Move',title:"Even <span class='glow-word'>This</span> Day Counts",body:["Some days, getting out of bed is the achievement. These feel small to everyone else, and enormous to you \u2014 and <span class='glow-word'>both things are true at once</span>.","On the days when you can barely move: you still count. This day still counts. <span class='glow-word'>The effort still matters</span>.","Healing isn't linear. Some days are just survival. You're still here. <span class='glow-word'>That's everything</span>."],signature:"You don't have to be okay. You just have to be here.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'who-you-are',tag:'A Truth About You',title:"This Is <span class='glow-word'>Who You Are</span>",body:["You are not your worst day. You are not your hardest season.","You are the person who reached out. Who tried again. Who, despite everything, still <span class='glow-word'>cares enough to feel this</span>.","That person is worth believing in \u2014 worth every good thing that's still on its way."],signature:"You are more than the hard parts.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'look-at-you',tag:'A Toast to You',title:"Look at <span class='glow-word'>What You Did</span>",body:["Stop for a second and actually look at what you've accomplished. Not briefly. Not dismissively. Really look.","You set out to do something hard, and you did it. Through the doubt, the setbacks \u2014 you <span class='glow-word'>kept going and made it happen</span>.","This is your moment. Not luck. Not timing. <span class='glow-word'>You</span>."],signature:"Take the bow. You built this.",mood:'celebration',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'milestone',tag:'Marking the Moment',title:"This Moment <span class='glow-word'>Deserves</span> to Be Celebrated",body:["We spend so much time looking ahead that we forget to stop and <span class='glow-word'>celebrate where we actually are</span>.","The version of you from a year ago would be stunned. Would barely believe what you've managed to become.","<span class='glow-word'>Let yourself feel this</span>. You've earned the right \u2014 right here, in this moment you created."],signature:"You are exactly where you worked so hard to be.",mood:'celebration',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'how-far',tag:'Look How Far',title:"Remember <span class='glow-word'>Where You Started</span>",body:["Do you remember where you started? The fear. The uncertainty. The version of you that had no idea if any of this would work.","<span class='glow-word'>Look at you now</span>. Look at what that version of you built, decided, survived, and became.","You didn't just get lucky. You made choices. You refused to quit. <span class='glow-word'>That's worth celebrating loudly</span>."],signature:"Look how far you've come. Let yourself be proud.",mood:'celebration',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'grief-honored',tag:'For the Ones Who Are Hurting',title:"Your Grief Is <span class='glow-word'>Valid</span>",body:["Grief is not a problem to be solved. It's the price of love \u2014 and it is <span class='glow-word'>completely, fully valid</span>.","You don't have to be over it by now. You don't have to protect the people around you from how much this hurts.","Let yourself grieve. And know that <span class='glow-word'>love doesn't leave just because loss arrived</span>."],signature:"Grieve as long as you need. You loved that much.",mood:'grief',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'still-healing',tag:'The Long Road',title:"You Are <span class='glow-word'>Still Healing</span>",body:["Healing isn't a montage. It's messy and nonlinear \u2014 two steps forward, one step sideways, a day where everything feels fine and then suddenly <span class='glow-word'>it doesn't</span>.","That's not relapse. That's what healing actually looks like for real people with real pain.","The fact that you're still trying, still showing up for yourself \u2014 <span class='glow-word'>that is remarkable</span>."],signature:"Healing isn't a straight line. Neither is yours.",mood:'grief',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'carried-too-long',tag:'Put It Down',title:"You've Carried This <span class='glow-word'>Long Enough</span>",body:["There's something you've been holding for a long time. Maybe guilt. Maybe shame. Whatever it is \u2014 you've been carrying it <span class='glow-word'>far longer than you should have</span>.","It was never yours to keep forever.","You can set it down. You're allowed to <span class='glow-word'>walk a little lighter</span> from here."],signature:"You are allowed to let it go.",mood:'grief',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'broken-open',tag:'On the Other Side of Pain',title:"You Were <span class='glow-word'>Broken Open</span>, Not Broken",body:["There's a difference between being broken and being broken open. Broken-open people discover spaces inside themselves they never knew existed. <span class='glow-word'>Capacity they didn't know they had</span>.","What happened to you was real. The pain was real. But you are still here.","You weren't broken. You were <span class='glow-word'>broken open</span>. And what comes out is something the pain never expected: you, more fully yourself than ever before."],signature:"Pain broke you open. It didn't break you.",mood:'grief',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'start-here',tag:'A New Beginning',title:"Start <span class='glow-word'>Where You Are</span>",body:["You don't need the perfect plan. You don't need all the answers. You don't need permission from anyone to begin again.","Every great thing started with a single, imperfect step \u2014 made not because the path was clear, but because <span class='glow-word'>staying still hurt more</span>.","Wherever you are right now \u2014 that's enough of a starting line. What matters is what you choose <span class='glow-word'>next</span>."],signature:"Today is a perfectly good day to begin.",mood:'courage',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'the-leap',tag:'For the Ones on the Edge',title:"Take the <span class='glow-word'>Leap</span>",body:["You've been standing at the edge of something for a while now. Thinking about it. Wondering if the timing is right.","Here's the truth: the timing is never perfect. The certainty you're waiting for doesn't come before you jump \u2014 it comes <span class='glow-word'>after</span>.","I genuinely believe \u2014 with everything I have \u2014 that <span class='glow-word'>you're ready</span>."],signature:"The net appears when you jump. Jump.",mood:'courage',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'brave-enough',tag:'On Being Brave',title:"You Are <span class='glow-word'>Brave Enough</span>",body:["Courage isn't the absence of fear. It's the decision that something else matters more than the fear.","You don't have to feel brave to be brave. You just have to act, even with shaking hands. Even with a heart that's absolutely terrified.","Maybe you just needed to hear someone say: <span class='glow-word'>I see how brave you are</span>."],signature:"You are braver than fear. You always have been.",mood:'courage',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'your-voice',tag:'Speak Up',title:"Your Voice <span class='glow-word'>Deserves</span> to Be Heard",body:["You have something to say. But somewhere along the way you learned to make yourself smaller, wait for permission that never came.","You don't need permission. Your story is exactly the kind <span class='glow-word'>someone out there desperately needs to hear</span>.","The world is better when <span class='glow-word'>your voice is in it</span>."],signature:"Say the thing. The right people will hear it.",mood:'courage',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'say-yes',tag:'The Open Door',title:"Say <span class='glow-word'>Yes</span> to the Thing",body:["There's a door open in front of you right now. A version of your life that feels too big to imagine.","You're not unqualified. You're not too late. The door is open because <span class='glow-word'>you are meant to walk through it</span>.","Say yes. The readiness comes after. <span class='glow-word'>Walk through the door</span>."],signature:"Yes is where your next life begins.",mood:'courage',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'imperfect-beautiful',tag:'For the Imperfect Ones',title:"<span class='glow-word'>Imperfect</span> and Beautiful",body:["You're not supposed to have it all together. Perfection is a performance. <span class='glow-word'>You are something better</span> \u2014 you are real.","Textured. Honest. A person who shows up with flaws and heart and genuine effort.","That realness is your greatest gift. <span class='glow-word'>You are exactly enough</span> \u2014 cracks and all."],signature:"The broken places are where the light gets through.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'small-joys',tag:'The Little Things',title:"Let the <span class='glow-word'>Small Things</span> Matter",body:["On the hard days, pay attention to the small things. The coffee that was exactly right. The song that found you when you needed it.","These aren't distractions. <span class='glow-word'>They are the hard stuff's antidote</span> \u2014 proof that beauty persists even when everything else feels heavy.","<span class='glow-word'>Let them count</span>. The world is still making beauty, even now, even for you."],signature:"The small joys are still joys. Let them in.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'enough-for-today',tag:'Just Today',title:"<span class='glow-word'>Today</span> Is Enough",body:["You don't have to solve everything today. You don't have to figure out the next five years.","You just have to get through today. Not perfectly \u2014 <span class='glow-word'>just through it</span>. One conversation, one meal, one breath at a time.","Today is all you have to handle. And you are absolutely capable of <span class='glow-word'>handling today</span>."],signature:"One day at a time. Today counts.",mood:'comfort',visibility:'public',author:'Glow Notes',forWho:''},
  {id:'legacy',tag:'The Long View',title:"Think About <span class='glow-word'>Your Legacy</span>",body:["Not legacy in the headlines sense. Legacy in the true sense \u2014 the way you changed the room by being in it.","You are already building that. Every honest conversation. Every moment you chose compassion. Every time you showed up when you didn't have to.","<span class='glow-word'>That's legacy</span>. And yours is more alive than you realize."],signature:"You're already building something that lasts.",mood:'hopeful',visibility:'public',author:'Glow Notes',forWho:''}
];

// Helper: get reel by id
function getReelById(id) {
  return DEFAULT_REELS.find(r => r.id === id);
}

// Helper: get featured reels for grid
function getFeaturedReels() {
  return FEATURED_IDS.map(id => getReelById(id)).filter(Boolean);
}
